name: simpleclub_challenge
description: Simpleclub interview test task

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  bloc: ^8.0.2
  flutter_bloc: ^8.0.1
  dio: ^4.0.4
  animations: ^2.0.2
  equatable: ^2.0.3
  json_annotation: ^4.4.0
  flutter_native_splash: ^2.0.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4
  json_serializable: ^6.1.4
  build_runner: ^2.1.7
  flutter_launcher_icons: ^0.9.2

flutter:
  uses-material-design: true

flutter_icons:
  image_path: "assets/icon.png"
  android: true
  ios: true
  remove_alpha_ios: true
